default:
	@echo publish, view

publish:
	scp -pr ddx3x.pdf pshannon@trena:/data/dockerizedFlask/static/slides/erythropoiesis

view:
	open https://igv-data.systemsbiology.net/static/slides/erythropoiesis/ddx3x.pdf
