default:
	@echo publish, view, mkdir

publish:
	scp -pr mtor.pdf pshannon@trena:/data/dockerizedFlask/static/slides/mouse/

view:
	open https://igv-data.systemsbiology.net/static/slides/mouse/mtor.pdf

mkdir:
	ssh pshannon@trena mkdir /data/dockerizedFlask/static/slides/mouse

